[package]
name = "impedance"
version = "0.1.1"
authors = ["Gus Wynn <guswynn@gmail.com>"]
edition = "2018"
description = "Tools to mix blocking and async code"

license = "MIT OR Apache-2.0"
repository = "https://github.com/guswynn/impedance"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.7.2"
parking_lot = "0.11.1"
pin-project = "1.0.7"
tokio = { version = "1.5.0", features = ["rt", "macros", "sync"] }
