name: Actions

on: 
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test on stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Stable
        run: rustup update stable
      - name: cargo test
        run: cargo test
      - name: test rayon module
        run: cargo test --features rayon
      - name: cargo test async_std
        run: cargo test --no-default-features --features async-std-experimental
  bench:
    name: Bench on nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Nightly
        run: rustup update nightly
      - name: cargo +nightly bench
        run: cargo +nightly bench
